-- Cargo+420 starter data (edit everything from the owner dashboard)
insert into public.store_settings (id) values (1) on conflict do nothing;
-- private_config (push keys + function URL) is filled in directly on the server, not stored in git
insert into public.zones (min_order, fee, cities, sort) values
(40,0,array['Detroit','Hamtramck','Hazel Park','Highland Park','Southfield','Lathrup Village','Oak Park'],0),
(65,15,array['Berkley','Beverly Hills','Birmingham','Clawson','Dearborn Heights','Eastpointe','Ferndale','Fraser','Grosse Pointe','Grosse Pointe Woods','Harper Woods','Huntington Woods','Inkster','Madison Heights','Redford','River Rouge','Royal Oak','Roseville','St Clair Shores','Warren','Allen Park'],1),
(100,20,array['Farmington Hills','Harrison Twp','Livonia','Northville','Novi','Rochester','Romulus','Taylor','Trenton','Troy','West Bloomfield','Wayne','Westland','Woodhaven','Sterling Heights','Van Buren','Wixom','Belleville','Canton'],2),
(125,30,array['Auburn Hills','Bloomfield Hills','Commerce','Clinton Township','Keego Harbor','Mount Clemens','Milford','Pontiac','Sylvan Lake','Rockwood','Utica','Waterford'],3),
(150,40,array['Ann Arbor','Brighton','Clarkston','Lake Orion','New Haven','New Baltimore','Shelby Twp','South Lyon','Ypsilanti'],4);
insert into public.tiers (id, name, price, pct_off, waive_fee, perks, sort) values
('gold','Gold',25,10,false,array['10% off every order','Priority dispatch','Members-only drops','Monthly member pricing'],1),
('platinum','Platinum',50,15,true,array['15% off every order','City minimum fee waived','Early access to new strains','Member events (+1 guest)'],2),
('black','Black Card',100,20,true,array['20% off every order','City minimum fee waived','Exclusive strains & first pick','VIP events + 2 guests','Birthday gift drop'],3);
insert into public.products (name, cat, price, stock, tags, thc, size, strain, description, featured) values
('GMO','flower',20,12,array['Indica','3.5 grams']::text[],'29% THC','3.5g','Indica','Garlic-funk indica. Heavy body, late-night pick.',false),
('Carbon Fiber','flower',25,12,array['Hybrid']::text[],'31% THC','3.5g','Hybrid','Dense purple-tinted buds with a fuel-and-grape nose.',true),
('Lemon Cheesecake','flower',20,12,array['Hybrid']::text[],'26% THC','3.5g','Hybrid','Bright citrus up front, creamy finish.',false),
('Sherb Cream Pie','flower',25,12,array['Indica Dominate Hybrid']::text[],'28% THC','3.5g','Indica-dominant','Sweet sherbet terps, relaxed and social.',false),
('Bolo Runtz','flower',25,12,array['Hybrid']::text[],'30% THC','3.5g','Hybrid','Candy-forward Runtz cut.',false),
('Candy Cake','flower',20,12,array['Indica']::text[],'27% THC','3.5g','Indica','Vanilla-sugar nose, easy evening smoke.',false),
('Pink Rozay','flower',45,12,array['Hybrid']::text[],'32% THC','7g','Hybrid','Top shelf. Floral, fruity, frosty.',true),
('Lemon Haze','flower',20,12,array['Sativa']::text[],'25% THC','3.5g','Sativa','Daytime sativa with a sharp lemon-peel pop.',false),
('SFV OG','flower',25,12,array['Indica']::text[],'28% THC','3.5g','Indica','Classic piney OG.',false),
('House Ounce','flower',75,12,array['$75 Ounce']::text[],'22–25% THC','28g','Mixed','Budget ounce, rotating strain.',false),
('Top Shelf Ounce','flower',100,12,array['$100 Ounces']::text[],'27%+ THC','28g','Mixed','Premium ounce, rotating strain.',true),
('Smalls 3.5g','flower',15,12,array['3.5 grams']::text[],'24% THC','3.5g',null,'Small buds, same quality.',false),
('Shake Half-Oz','flower',35,12,array['Shake']::text[],null,'14g',null,'Great for rolling and cooking.',false),
('$25 Snack Pack','flower',25,12,array['Pre rolls','Package Deals']::text[],null,'5 pre-rolls + snacks',null,'Five pre-rolls bundled with snacks.',false),
('Chocolate Rice Crispy Treat','edibles',10,12,array['Treats']::text[],'100mg',null,null,'Chocolate-dipped crispy square.',false),
('Berry Cereal Bar','edibles',12,12,array['Treats']::text[],'200mg',null,null,'Fruity cereal bar.',false),
('THC Suckers','edibles',7,12,array['Candy']::text[],'50mg',null,null,'Assorted flavors.',false),
('THC Taffy 2-Pack','edibles',7,12,array['Candy']::text[],'100mg',null,null,'Chewy taffy, two pieces.',false),
('Chex Mix','edibles',10,12,array['Snacks']::text[],'100mg',null,null,'Savory infused snack mix.',false),
('Rice Krispy Treat','edibles',8,0,array['Treats']::text[],'100mg',null,null,'Classic marshmallow treat.',false),
('Gummies 10-Pack','edibles',20,12,array['Gummies']::text[],'100mg (10×10mg)',null,null,'Mixed fruit gummies.',true),
('CBD Tincture 1000mg','cbd',35,12,array['Tincture']::text[],'0% THC',null,null,'Full-spectrum CBD oil, 30ml.',false),
('CBD Gummies','cbd',25,12,array['Gummies']::text[],null,null,null,'25mg CBD each, 20 count.',false),
('CBD Pre-rolls 3-Pack','cbd',15,12,array['Pre rolls']::text[],null,null,null,'Hemp flower pre-rolls.',false),
('CBD Relief Balm','cbd',20,12,array['Topical']::text[],null,null,null,'500mg CBD, menthol + arnica.',false),
('Hash Burger','concentrates',35,12,array['Hash']::text[],null,'1g',null,'Pressed hash disc.',false),
('Live Resin Badder','concentrates',30,12,array['Badder']::text[],'78% THC','1g',null,'Whipped live resin.',false),
('Kief','concentrates',20,12,array['Kief']::text[],null,'2g',null,'Sift kief. Top your bowl.',false),
('Moon Rock','concentrates',15,12,array['Moon Rock']::text[],null,'1g',null,'Flower dipped in oil, rolled in kief.',false),
('RSO Pills','concentrates',20,12,array['RSO']::text[],null,'per pill',null,'Priced per pill.',false),
('Lion’s Mane Capsules','mushrooms',30,12,array['Functional']::text[],null,'60 ct',null,'Functional mushroom supplement.',false),
('Reishi Chocolate Bar','mushrooms',18,12,array['Functional']::text[],null,null,null,'Dark chocolate with reishi extract.',false),
('Mushroom + THC Gummies','mushrooms',28,12,array['Mushroom + THC']::text[],'100mg',null,null,'Functional mushroom blend with THC.',false),
('2g Disposables','vapes',22,12,array['Disposable Vape']::text[],null,'2g',null,'Assorted strains, rechargeable.',false),
('Kayo Mini 3.5g Grape Ape','vapes',42.5,12,array['Disposable Vape']::text[],null,'3.5g',null,'Big-capacity disposable.',false),
('Cutleaf Duos Pop & Dab (Blue Gelato)','vapes',32,12,array['Disposable Vape','Hybrid']::text[],null,null,null,'Dual-chamber disposable.',true),
('Cutleaf Duos Pop & Dab (Fruit Punch)','vapes',32,12,array['Disposable Vape','Sativa']::text[],null,null,null,'Dual-chamber disposable.',false),
('510 Vape Battery','vapes',12,12,array['Vape Battery']::text[],null,null,null,'Variable voltage, USB-C.',false),
('THC Arousal Oil','enhance',30,12,array['Oils']::text[],null,null,null,'Infused intimacy oil.',false),
('Libido Gummies','enhance',25,12,array['Gummies']::text[],null,null,null,'Herbal blend gummies.',false),
('Intimacy Bath Bomb','enhance',15,12,array['Bath']::text[],null,null,null,'CBD bath bomb.',false),
('Zig-Zag Hemp Wraps','smoke',1,12,array['Wraps']::text[],null,null,null,null,false),
('Elements Papers','smoke',1.5,12,array['Papers']::text[],null,null,null,null,false),
('Bob Marley Wraps','smoke',2,12,array['Wraps']::text[],null,null,null,null,false),
('Spray Can Lighter Torch','smoke',25,12,array['Lighters']::text[],null,null,null,null,false),
('Herb Grinder','smoke',15,12,array['Herb Grinders']::text[],null,null,null,null,false),
('Weed Rolling Tray','smoke',5,12,array['Pipes & Accessories']::text[],null,null,null,null,false),
('Zig-Zag 6 Pack Organic Cones','smoke',2.25,12,array['Papers']::text[],null,null,null,null,false),
('Hangover Cure','smoke',3,12,array['Smokers Supplies']::text[],null,null,null,null,false);
